/*
* ============================================================================
*  Name     : CMesayngers60v2Document from Mesayngers60v2Document.h
*  Part of  : mesayngers60v2
*  Created  : 4/9/2024 by adinandradrs
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: 
* ============================================================================
*/

#include "Mesayngers60v2Document.h"
#include "Mesayngers60v2AppUi.h"

CMesayngers60v2Document::CMesayngers60v2Document(CEikApplication& aApp) : CAknDocument(aApp) {
}

CMesayngers60v2Document::~CMesayngers60v2Document() {
}

void CMesayngers60v2Document::ConstructL() {
}

CMesayngers60v2Document* CMesayngers60v2Document::NewL(CEikApplication& aApp) {
    CMesayngers60v2Document* self = new (ELeave) CMesayngers60v2Document( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();
    return self;
}
    
CEikAppUi* CMesayngers60v2Document::CreateAppUiL() {
    return new (ELeave) CMesayngers60v2AppUi;
}